### ISSUE TITLE
Alterar home_page_switcher para tratar vários papéis no client

### ISSUE THREAD

**Issue by goiaba** [goiaba/sisen#2]
O home_page_switcher tem uma cadeia de if/else que retorna a página inicial do usuário, mas ela precisa levar em consideração o papel escolhido no cliente.

**Comment by rafacamargo123** [comment]
Problema acontece porque o papel é definido baseado nos models Student e Professor, que buscam nas tabelas students e professors, respectivamente, e não nos grupos do usuário do django

**Comment by goiaba** [comment]
Criada branch [issue#2](https://github.com/goiaba/sisen/tree/issue%232) com possível solução...

**Comment by goiaba** [comment]
Solucionado pelo commit b670cb3f98602c421b92c66555a438e49ca77c75
