### ISSUE TITLE
Corrigir a carga das respostas

### ISSUE THREAD

**Issue by goiaba** [goiaba/sisen#27]
O problema é que o código considera que as questões foram inseridas no banco ordenadamente (1,2,3..), o que não é necessariamente verdade. Elas são inseridas de acordo com a study option da qual fazem parte. Por exemlo, para Estilos de aprendizagem a inserção é fora de ordem:

https://github.com/goiaba/sisen/blob/b31d31337cde95baaee1da43c4e0dce3cdc44648/documentation/dataLoad.txt#L31

Mas para Inteligências Múltiplas, ordenado:

https://github.com/goiaba/sisen/blob/b31d31337cde95baaee1da43c4e0dce3cdc44648/documentation/dataLoad.txt#L145

Teríamos que pensar em outra abordagem aqui:

https://github.com/goiaba/sisen/blob/b31d31337cde95baaee1da43c4e0dce3cdc44648/server/sisen/survey/tests.py#L50

**Comment by goiaba** [comment]
Corrigido e aberto PR #32

**Comment by rafacamargo123** [comment]
closed by #32
