### ISSUE TITLE
Tratar caso em que não há papel associada a usuário

### ISSUE THREAD

**Issue by goiaba** [goiaba/sisen#31]
Corrigir método `setRoleAndNavigateToRoot` do `viewmodels/app/app.js` para tratar casos em que usuário não possui nenhum papel. O comportamento atual deixa o usuário numa tela vazia, sem possibilidade de logout (é necessário remover a sessão do storage manualmente para conseguir sair).

Se não houver papel, exibir mensagem e encerrar sessão (logout).

**Comment by rafacamargo123** [comment]
@goiaba isso foi resolvido no https://github.com/goiaba/sisen/pull/34/commits/72e7d223440c4eff45ab89967fea968b78821716?

**Comment by goiaba** [comment]
Sim, encerrando.
