### ISSUE TITLE
Corrigir signup após logout

### ISSUE THREAD

**Issue by rafacamargo123** [goiaba/sisen#35]
Erro "error decoding signature" ao abrir a tela de signup logo após fazer logout

**Comment by rafacamargo123** [comment]
When user logs out, sessionCleanup is called, which updates AuthInterceptor, which sets token to NULL.
Then, the AuthInterceptor was adding the JWD header without value

**Comment by goiaba** [comment]
Closed by 22f2eb43654ede2235a98bf36b7aa900142732d0
